### ISSUE TITLE
Historia 1: Registro e inicio de sesión: Implementación del Back-end

### ISSUE THREAD

**Issue by Pathyfernandez** [No-Country-simulation/h2-01-n-node-react#10]

**Comment by Pathyfernandez** [comment]
Gestión de usuarios:

Crear los endpoints para el registro, inicio de sesión y validación de credenciales:
Registro: Recibe los datos del usuario y almacena las credenciales en la base de datos.
Login: Verifica si el email y la contraseña coinciden con un usuario existente.
Implementar lógica de validación de datos en el servidor (verificar si el email ya existe, encriptación de contraseñas, etc.).
Autenticación y Seguridad (1 Back-end):

Implementar autenticación segura mediante tokens (JWT) o sesiones.
Encriptar las contraseñas usando bcrypt u otro algoritmo seguro.
Configurar un sistema de recuperación de contraseñas (envío de emails, restablecimiento de credenciales).

**Comment by jp-quintana** [comment]
@spimentel1201 @Pathyfernandez ya arranque con este modulo. Tambien arme una rama `back-dev` con la configuracion inicial de nest y pg. Digo de crear ramas nuevas para cada feature partiendo de esa rama y mergeamos ahi y no a main.

**Comment by Pathyfernandez** [comment]
Me parece perfecto

**Comment by jp-quintana** [comment]
@Pathyfernandez favor podras crear una historia nueva para el recupero de contraseña. Quiero que los chicos del front puedan hacer la conexion y una vez este ok eso me pongo con el recupero!
